### ISSUE TITLE
TaffyDB is not working on Safari 9 (OSX 10.10.5)

### ISSUE THREAD

**Issue by zhenrong** [typicaljoe/taffydb#100]
Hi,

TaffyDB tests fail completely on OSX 10.10.5 Safari 9 (10601.1.56). At the moment, Safari 9 is only available as a beta download. But in a few days time, it will be available on App Store.

Does anyone have a fix for this? At the moment, i am still trying to debug the library but no luck.

**Comment by ltullman** [comment]
Hi, I posted a fix here:

https://github.com/typicaljoe/taffydb/issues/98

**Comment by ltullman** [comment]
https://github.com/typicaljoe/taffydb/pull/101

**Comment by viniciusbo** [comment]
Did work for me, thanks! @typicaljoe seems to be AFK for a very long time.

**Comment by mmikowski** [comment]
See #101 .  Fixed.
