### ISSUE TITLE
db().sum() with floats inside quotations

### ISSUE THREAD

**Issue by SeaRoth** [typicaljoe/taffydb#119]
Hi, the function sum() thinks my floats are strings.

- **Example:** db().sum("close") returns 29.2932.15 instead of 61.44.  

- **Note**: The db created below is from a json_encoded array from a php query that returns all values from a mysql table.

- **Note2** I know I could do the calculations in PHP but I own a shared web hosting account that limits my CPU and RAM and with 3000+ records it's painful.

var db = TAFFY(
[
{"id":"1","date":"2016-05-24","symbol":"aaap","ask":"29.29","open":"29.17","close":"29.29","outstandingShares":"39278000","monthsIncreasingShortInterest":"3","percentDeclinedYesterday":"2.083","beta":"-0.432","yearHighpercentDiff":"-26.15","maxDaysGapTrading":"0,1,2,3,4,5,6,7,8,9","averageDailyVolume":"45279","shortRatio":"3.38","___id":"T000002R000002","___s":true},

{"id":"2","date":"2016-05-24","symbol":"aal","ask":"32.32","open":"31.89","close":"32.15","outstandingShares":"578171000","monthsIncreasingShortInterest":"2","percentDeclinedYesterday":"1.306","beta":"0.001","yearHighpercentDiff":"-31.73","maxDaysGapTrading":"0,1,2,3,4,5,6,7,8,9","averageDailyVolume":"8927850","shortRatio":"3.82","___id":"T000002R000003","___s":true} ]);

-Thank you
coryr32@gmail.com

**Comment by SeaRoth** [comment]
I have made a workaround in the meantime:

```
var lastOneDay = <?php echo (json_encode($_SESSION["test"])); ?>;
for(var i=0; i<lastOneDay.length; i++){
	var row = JSON.stringify(lastOneDay[i]);				
	var n = row.indexOf("close") + 7;
	var m = row.indexOf("outstandingShares") - 2;				
	var target = row.substring(n,m);
	target = target.replace(/["']/g, "");
	row = row.replaceBetween(n,m,target);
	lastOneDay[i] = row;
}
```



```
String.prototype.replaceBetween = function(start, end, what) {
	return this.substring(0, start) + what + this.substring(end);
};
```

I doubt this is the most efficient way, I am just trying to get the job done.  Thank you for TaffyDB contributors!

**Comment by nathanfiscus** [comment]
Have you tried changing your PHP code for json_encode to use numeric detection:
`json_encode($_SESSION["test"], JSON_NUMERIC_CHECK)`

**Comment by SeaRoth** [comment]
I am very grateful for your informative reply and thank you for bringing this to my attention.  Good day to you sir!
