### ISSUE TITLE
How to operate taffyDB JSON sample like this?

### ISSUE THREAD

**Issue by webloong** [typicaljoe/taffydb#125]
var friends = TAFFY([{
    people:[
        { "id": 1, "gender": "M", "first": "John" },
        { "id": 2, "gender": "F", "first": "Kelly" },
        { "id": 3, "gender": "M", "first": "Jeff" },
        { "id": 4, "gender": "F", "first": "Jennifer" }
    ]
}]);

I've tried

friends({people.gender: "M", people.first: "John"});
but that doesn't work either.

**Comment by typicaljoe** [comment]
Typically you should just include the array and not the People object. So something like this:

`var friends = TAFFY([
{ "id": 1, "gender": "M", "first": "John" },
{ "id": 2, "gender": "F", "first": "Kelly" },
{ "id": 3, "gender": "M", "first": "Jeff" },
{ "id": 4, "gender": "F", "first": "Jennifer" }
]);
friends({gender:"M"}).get();
`

**Comment by webloong** [comment]
SO , This means that JSON data must be  level 1 ?

**Comment by typicaljoe** [comment]
Correct. While you can use the has filter to do some deep object inspection on queries all you'd get back in your above example is a copy of the people object with the array.

On a side note, I do use JSON to organize the DBs. Something like this:

```javascript
var dbs = {
    people:TAFFY(),
    places:TAFFY(),
    pets:TAFFY()
}
```
This let's you keep your data organized in a tidy namespace while still using TAFFY to maintain the record collections. This is an example of where I look up the ID for my friend BOB when adding a pet to the pets DB:

```javascript
dbs.pets.insert({name:'Button',type:'Dog',owner:dbs.people({firstName:"Bob"}).first().id});
```

**Comment by webloong** [comment]
thanks!!
