### ISSUE TITLE
Version on npm is not up-to-date?

### ISSUE THREAD

**Issue by matthewgertner** [typicaljoe/taffydb#126]
I might be missing something obvious but I installed the version at https://www.npmjs.com/package/taffydb and I'm not seeing the iOS 9 fix landed last October (https://github.com/typicaljoe/taffydb/pull/101). The reported version is the same as in `master` however (2.7.2). Is it possible that the npm version has been updated since that fix was landed and the version number wasn't bumped in `master`?

**Comment by mmikowski** [comment]
@matthewgertner i will republish the npm package.  Last I knew, however, it was 2.7.2.  The new version will be 2.7.3, and will definitely be the latest code.

**Comment by matthewgertner** [comment]
Cool, thanks!
