### ISSUE TITLE
Maintaining NPM

### ISSUE THREAD

**Issue by mcwhittemore** [typicaljoe/taffydb#127]
Does anyone who has contributed to this project want to maintain the npm module? There are a few open tickets here about npm and bower and https://github.com/jsdoc3/jsdoc/issues/961 has been having problems too.

**Comment by typicaljoe** [comment]
@mmikowski and myself would both like it be on it.

**Comment by mcwhittemore** [comment]
What are the npm usernames I should add (neither or your github names are npm user names).

**Comment by typicaljoe** [comment]
My NPM one is biastoact. I'm not sure about Mike's.

**Comment by mcwhittemore** [comment]
@typicaljoe I added you so you should be able to add others later. Closing this for now.

**Comment by mmikowski** [comment]
@typicaljoe @mcwhittemore My npm username is mikem.  Here is a link to my beauty shot.  https://www.npmjs.com/~mikem

**Comment by mcwhittemore** [comment]
Just added you @mmikowski. Thanks :)
