### ISSUE TITLE
Issue calling .update() from function

### ISSUE THREAD

**Issue by billmalcolm** [typicaljoe/taffydb#140]
Hi there!
I'm having trouble updating a record, when I call the method from another function. I call the DB.Handler function in my init function. I was able to insert and get just fine, so I can connect at least. I can run the update from the console by just calling TS.DB.Projects({ id: 2 }).update({"name": "WTF", "code": 789, "notes": "some notes", "lastUpdate": 84851634665 }); and that works, but calling the function from the addEventListener seems to cause the update to fail.

Maybe I'm missing something. Let me know if you need more 

FYI: I added another field called id and just increment that based on the the max value

Here's my code:

`TS.DB = {
    Projects: TAFFY(),
    Times: TAFFY(),
    DBhandler: function () {
        TS.DB.Projects();
        TS.DB.Times();
        TS.DB.Projects.store("projects");
        TS.DB.Times.store("time");
    },
    editProject: function () {
        var pID = document.getElementById('projectID').value;        
        var newName = document.getElementById('editName').value;
        var newCode = document.getElementById('editCode').value;
        var newNotes = document.getElementById('editNotes').value;
        var updated = new Date().getTime();        
        TS.DB.Projects({ "id": pID }).update({ "name": newName, "code": newCode, "notes": newNotes, "lastUpdate": updated });`

`document.getElementById('saveEdits').addEventListener('click', function () {
            TS.DB.editProject();
 });`

`<form id="editProjectForm">
                    <input type="hidden" id="projectID" value="" />
                    <label for="editName">Project Name</label><input id="editName" type="text" /><br /><br />
                    <label for="editCode">Project Code</label><input id="editCode" type="text" /><br /><br />
                    <label for="editNotes">Notes</label><textarea id="editNotes"></textarea><br /><br />
                    <button id="saveEdits" type="button">Save Project</button>
                    <button class="cancelModal">Cancel</button>
                </form>`

**Comment by billmalcolm** [comment]
I forgot to include the closing brackets in the first block here. They were in my project, I just forgot to include them above. The editProject() does indeed run error free, but the update() operation doesn't even seem to fire

**Comment by billmalcolm** [comment]
Ok, so I putzed with this and I think the problem comes from trying to use a var/function to determine the id when matching a record to update. It works when I hard code the value, but trying to pass it in otherwise doesn't seem to work

**Comment by typicaljoe** [comment]
Good clue, I'm going to guess it is a type conversion issue. So if the ID in the DB is a number, the id value pulled out of the HTML will be a string. Wrapping the value in parseInt() will probably do the trick.

**Comment by billmalcolm** [comment]
Yeah buddy! That seems to work, thanks!
