### ISSUE TITLE
Get() with filter no working

### ISSUE THREAD

**Issue by Joslovefun** [typicaljoe/taffydb#148]
Code:
112:		console.log(my_index().stringify());
113:		console.log(my_index({id:1}).get());
Console LOG:
JoeDocs.html:112 [{"id":[1],"OS":["Linux"],"Type":["Document"],"Head":["Setup OpenVMS cluster"],"Doc":["Set up linux cluster :0: Steps to perform "],"___id":"T000003R000002","___s":true},{"id":[2],"OS":["Unix"],"Type":["Document"],"Head":["Setup OpenVMS cluster"],"Doc":["Set up Unix cluster :0: Steps to perform "],"___id":"T000003R000003","___s":true},{"id":[3],"OS":["OpenVMS"],"Type":["Document"],"Head":["Setup OpenVMS cluster"],"Doc":["Set up OpenVMS cluster :0: Steps to perform "],"___id":"T000003R000004","___s":true}]

JoeDocs.html:113 []length: 0__proto__: Array(0)

Could you please let me know why "console.log(my_index({id:1}).get());" this is not returning anything? 

Thanks!

**Comment by typicaljoe** [comment]
It appears your id column has the number one stored in an array. Be default the match isn't greedy enough to look into an array. I'd suggest switching to {id:1 in your record and see how that goes. An alternative that might work (but I haven't tested) would be to use 'has':

> my_index({id:{has:1}}).get()
