### ISSUE TITLE
Delete DB entry or the whole DB

### ISSUE THREAD

**Issue by janstieler** [typicaljoe/taffydb#150]
Hi,

how can I delete an entry in the DB or delete the whole DB?
I havn't found anything about in the documenattion and width `window.localStorage.clear();` I get an `undefinied` error.

Kindly

**Comment by typicaljoe** [comment]
Doing a db().remove() will remove all the records and if you used .store() to take advantage of localStorage that change will be passed on to localStorage as well (essentially leaving just an empty array in localStorage).
