### ISSUE TITLE
Include a LICENSE file

### ISSUE THREAD

**Issue by alex-deas** [typicaljoe/taffydb#151]
Automated tools which authenticate copyright compliance with dependencies don't always parse the config file. It would be nice to include the ~~MIT~~ BSD-2-Clause license in a LICENSE.md file to help these tools out :)

**Comment by josecolella** [comment]
@alex-deas I also agree with this especially for enterprises that use this db, having an unknown licenses means that the source code is not open source

**Comment by josecolella** [comment]
@alex-deas  I added a pull request https://github.com/typicaljoe/taffydb/pull/152, that includes an MIT license. Hopefully it gets pulled in soon

**Comment by josecolella** [comment]
With commit https://github.com/typicaljoe/taffydb/commit/3b4d88feca6cdae3a33bbbf554a0f55b682535d2, you can close this. Thanks Joe.
