### ISSUE TITLE
Query based on array. Eg db({ data[2]: 'true' })

### ISSUE THREAD

**Issue by coisox** [typicaljoe/taffydb#153]
Lets say:
`
db = TAFFY([
  {"color": ["red", "blue"], "price":3},
  {"color": ["blue", "yellow"] "price":2},
  {"color": ["green", "purple"] "price":1}
]);
`

How to:
1. select records which have blue in first array for key = color?
2. select records which have blue in either first or second array for key = color?

**Comment by typicaljoe** [comment]
I don't think you can control for location using the object selectors. What you can do is pass in a function. Something like what I have below. By returning true you tell taffy that it matches your filter and to return the record:
`db(function () {
   if (this.color[0] == 'blue') {
     return true;
    }
   return false;
})`

**Comment by coisox** [comment]
i see thank you
