### ISSUE TITLE
Where does taffy db stores data ?

### ISSUE THREAD

**Issue by mayurbaldha** [typicaljoe/taffydb#155]
is it in local storage or indexeddb of browser or something else ?

**Comment by typicaljoe** [comment]
TaffyDB store data in memory - as a Javascript array. And I like any other Javascript array it is purged on page refresh (browser) or restart (node.js). You can use the .store() method to store your TaffyDB in the browser's localStorage though. But most folks push and pull data to the server and use TaffyDB to interact with and manage the data client side.
