### ISSUE TITLE
Official website seems to be down

### ISSUE THREAD

**Issue by lagosnomad** [typicaljoe/taffydb#169]
The official website seems to be down making the official documentation inaccessible.

![image](https://user-images.githubusercontent.com/8760121/103327435-d79c8700-4a54-11eb-8cc8-9f423da5f399.png)

**Comment by samihoda** [comment]
Down for me as well.

**Comment by moishinetzer** [comment]
Still down

**Comment by matthewstyers** [comment]
In the meantime, long live the wayback machine. https://web.archive.org/web/20200816113250/https://taffydb.com/

**Comment by faisal-qureshi** [comment]
@matthewstyers Thank you for that. One tends to forget the existence of this scary archive. Where all our sins of the past, live on :-)

**Comment by danielzzz** [comment]
still down..

**Comment by typicaljoe** [comment]
Attempting to fix. It actually just points to the /docs part of the GitHub but I moved the domain name and broke everything...

**Comment by typicaljoe** [comment]
This works for the moment:

http://typicaljoe.github.io/taffydb/

**Comment by samihoda** [comment]
Doesn't work for me.

**Comment by moishinetzer** [comment]
> This works for the moment:
> 
> http://typicaljoe.github.io/taffydb/

This doesn't seem to work

**Comment by danielzzz** [comment]
maybe this would help:
https://pages.github.com/

**Comment by typicaljoe** [comment]
Finally fixed. Looks like HTTPS should be fixed within 24 hours as well.
