### ISSUE TITLE
Adding records after and before other records

### ISSUE THREAD

**Issue by DanielRuf** [typicaljoe/taffydb#38]
Like mentioned on the wiki: https://github.com/typicaljoe/taffydb/wiki/Suggestions-and-New-Feature-Ideas

We could use the `.splice()` function or another solution for this?http://stackoverflow.com/a/4538364/753676

**Comment by mmikowski** [comment]
Hi Daniel:

I would like to reopen this issues , as I think this still should be an option.  Is this ok with you?

Cheers, Mike

ps. I can merge changes now as Ian has provided my with collaborator rights.  I still can dig up the 1.x code and if I can get it to work in 2.x.

**Comment by DanielRuf** [comment]
Sure, I'm ok with this.

**Comment by DanielRuf** [comment]
Is this issue still relevant?

**Comment by mmikowski** [comment]
I think it still is.  However, I've been so busy I haven't had time to attend to this.
